version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.21
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=etapaencontrar
      - discovery.seed_hosts=elasticsearch
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.21
    container_name: kibana
    ports:
      - "5601:5601"
      - "5602:5602"
    environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        - ELASTICSEARCH_PORT=9200
        - ELASTICSEARCH_PROTOCOL=http

volumes:
  esdata:
    driver: local

networks:
  elastic:
